
## 匯入資料(2選1就好)
### 1.連MySQL
```{r}
library(RMySQL)
library(DBI)
library(pool)
engine <- dbConnect(RMySQL::MySQL(),
                    host = "192.168.35.119",
                    port = 3306,
                    dbname = "dcard_db",
                    user = "derek",
                    password = "derek"
)

dbSendQuery(engine, 'set character set "Big5"'); #要先Send才能下一行的Get

Dcard1 <- dbGetQuery(engine,'select * from dcard_content;') #GetQuery得到dataframe

```

### 2.讀CSV
```{r}
Dcard1 <- read.csv("C:/Users/Student/Desktop/5-模型建立/RawData/DcardContent.csv")
```

### 只留要用的欄位
```{r}
Dcard2 = Dcard1[ ,c(3,4,5,6,7,8,12,15,16)]
rm(engine,Dcard1)
```

## 欄位處理
### 把time這欄換成上午 下午 晚上 半夜
```{r}
#把time欄位轉成時段 上午下午晚上半夜
Dcard2$time = substr(Dcard2$time ,1,2)
Dcard2$time = as.character(Dcard2$time)
b1=which(Dcard2$time=='07' |Dcard2$time=='08'|Dcard2$time=='09'|Dcard2$time=='10'|Dcard2$time=='11'|Dcard2$time=='12' )
Dcard2[b1,'time']='上午' 

b2=which(Dcard2$time=='13' |Dcard2$time=='14'|Dcard2$time=='15'|Dcard2$time=='16'|Dcard2$time=='17'|Dcard2$time=='18' )
Dcard2[b2,'time']='下午' 

b3=which(Dcard2$time=='19' |Dcard2$time=='20'|Dcard2$time=='21'|Dcard2$time=='22'|Dcard2$time=='23'|Dcard2$time=='00' )
Dcard2[b3,'time']='晚上' 

b4=which(Dcard2$time=='01' |Dcard2$time=='02'|Dcard2$time=='03'|Dcard2$time=='04'|Dcard2$time=='05'|Dcard2$time=='06' )
Dcard2[b4,'time']='半夜' 
rm(b1,b2,b3,b4)
```

### 對地區和星期幾都做一樣的事(等一下要攤平)
```{r}
Dcard2$area = as.character(Dcard2$area)
ar0=which(Dcard2$area==0)
Dcard2[ar0,'area'] ='其他地區'

ar1=which(Dcard2$area==1)
Dcard2[ar1,'area'] ='北區'

ar2=which(Dcard2$area==2)
Dcard2[ar2,'area'] ='中區'

ar3=which(Dcard2$area==3)
Dcard2[ar3,'area'] ='南區'

ar4=which(Dcard2$area==4)
Dcard2[ar4,'area'] ='東區'

ar5=which(Dcard2$area==5)
Dcard2[ar5,'area'] ='離島區'

Dcard2$weekday = as.character(Dcard2$weekday)
we1=which(Dcard2$weekday==1)
Dcard2[we1,'weekday'] ='星期一'

we2=which(Dcard2$weekday==2)
Dcard2[we2,'weekday'] ='星期二'

we3=which(Dcard2$weekday==3)
Dcard2[we3,'weekday'] ='星期三'
we4=which(Dcard2$weekday==4)
Dcard2[we4,'weekday'] ='星期四'
we5=which(Dcard2$weekday==5)
Dcard2[we5,'weekday'] ='星期五'
we6=which(Dcard2$weekday==6)
Dcard2[we6,'weekday'] ='星期六'
we7=which(Dcard2$weekday==7)
Dcard2[we7,'weekday'] ='星期日'
rm(ar0,ar1,ar2,ar3,ar4,ar5,we1,we2,we3,we4,we5,we6,we7)
```

###
```{r}
library(jiebaR)
library(tm)
library(tmcn) 
library(jsonlite)
work_user<-worker(user="C:/Users/Student/Desktop/5-模型建立/RawData/FO.csv",                  stop_word="C:/Users/Student/Desktop/5-模型建立/RawData/stop2.csv")

xtext2 = lapply(Dcard2$content,segment,jiebar=work_user)
Dcard2$content2 = xtext2 
Dcard2$content2 = as.character(Dcard2$content2)
Dcard2$content2 <-gsub("c","",Dcard2$content2) #把c去掉
Dcard2$content2 <-gsub('[(.*)]' , "" , Dcard2$content2) #把括號()清掉
Dcard2$content2 <-gsub("\"" , "",Dcard2$content2) #把"去掉
Dcard2$content2 <-gsub(',',"、",Dcard2$content2) #把,換成、
Dcard2$content2 <-gsub(" ","",Dcard2$content2) #把空格去掉

Dcard2$nchar1 =nchar(Dcard2$content)  #原文字元數
Dcard2$nchar2 =nchar(Dcard2$content2) #有效字元數
```

### 對類別欄位攤平-機器學習要攤平
```{r}
library(nnet)
Dcard3<- as.data.frame(cbind(Dcard2, 
                         class.ind(Dcard2$weekday),
                         class.ind(Dcard2$gender),
                         class.ind(Dcard2$area),
                         class.ind(Dcard2$time)))

Dcard4 = Dcard3[ ,c(9,8,11,12,13,14,15,16,17,18,19,22,23,24,25,26,27,28,29,30,31,32,33)]
rm(Dcard2,Dcard3,xtext2)
```

### 加入TF-IDF 關鍵字
```{r}
Dcard4$chocolate <-as.integer(str_count(Dcard4$content,"巧克力"))
Dcard4$cookie <- as.integer(str_count(Dcard4$content,"餅乾"))
Dcard4$butter <- as.integer(str_count(Dcard4$content,"奶油"))
Dcard4$strawberry <- as.integer(str_count(Dcard4$content,"草莓"))
Dcard4$cheese <- as.integer(str_count(Dcard4$content,"乳酪"))
Dcard4$milk <- as.integer(str_count(Dcard4$content,"牛奶"))
Dcard4$egg <- as.integer(str_count(Dcard4$content,"蛋"))
Dcard4$coffee <- as.integer(str_count(Dcard4$content,"咖啡"))
Dcard4$lemon <- as.integer(str_count(Dcard4$content,"檸檬"))
Dcard4$beef <- as.integer(str_count(Dcard4$content,"牛肉"))

Dcard5 = Dcard4[ ,-2]
#rm(Dcard4)
```

### 分訓練、測試資料
```{r}
library(caTools)
set.seed(11)
split =sample.split(Dcard5$heart , SplitRatio =0.8)
trainingset = subset(Dcard5, subset =(split==TRUE) )
testset = subset(Dcard5, subset =(split==FALSE) )
rm(split)
```


### 準備做XGBoost
```{r}
data.y <- Dcard5$heart
data.n <- Dcard5[ ,-1]

#分訓練測試資料 sample函數 從1:nrow(data)中 隨機挑選80%
select <- sample(1:nrow(Dcard5),nrow(Dcard5)*0.8)

train_set.x <- data.n[select,]
train_set.y <- data.y[select] #訓練資料的y
test_set.x <- data.n[-select,]
test_set.y <- data.y[-select] #測試資料的y
```


```{r}
library(xgboost)

#要把原本的Dataframe先換成xgboost的矩陣格式
#data放x欄位 ， label放y欄位
dtrain <- xgb.DMatrix(data = as.matrix(train_set.x), 
                      label =  as.matrix(train_set.y))

#測試資料只要X就好 label不用放
dtest <- xgb.DMatrix(data = as.matrix(test_set.x)) 

#設定參數
xgb.params = list(
  #col的抽樣比例，越高表示每棵樹使用的col越多，會增加每棵小樹的複雜度
  colsample_bytree = 0.5,                    
  #row的抽樣比例，越高表示每棵樹使用的col越多，會增加每棵小樹的複雜度
  subsample = 0.5,                      
  booster = "gbtree",
  #樹的最大深度，越高表示模型可以長得越深，模型複雜度越高
  max_depth = 2,           
  #boosting會增加被分錯的數據權重，而此參數是讓權重不會增加的那麼快，因此越大會讓模型愈保守
  eta = 0.04,
  # 或用'mae'也可以
  eval_metric = "rmse",                      
  objective = "reg:linear",
  #越大，模型會越保守，相對的模型複雜度比較低
  gamma = 0)

#先用xgb.cv()函數 為了知道建多少棵樹最好(重點!!))
cv.model = xgb.cv(
  params = xgb.params, 
  data = dtrain, #丟訓練資料
  nfold = 5,     # 5-fold cv
  nrounds=200,   # 各個樹總數下的模型 嘗試種200棵樹
  # 如果當nrounds <30時，就已經有過度擬合情況發生，那表示不用繼續調下去了，可以提早停止
  early_stopping_rounds = 30, 
  print_every_n = 50 # 每20顯示1次
)

tmp <- cv.model$evaluation_log #把log先存起來
```

### 畫圖
```{r}
plot(x=1:nrow(tmp), y= tmp$train_rmse_mean, col='red', xlab="nround", ylab="rmse", main="Avg.Performance in CV") 
points(x=1:nrow(tmp), y= tmp$test_rmse_mean, col='blue') 
legend("topright", pch=1, col = c("red", "blue"), 
       legend = c("Train", "Validation") )
```

### 正式建模
```{r}
best.nrounds = cv.model$best_iteration 
#best.nrounds 得到建多少顆樹最好

xgb.Model <- xgb.train(paras = xgb.params, 
                       data = dtrain, 
                       nrounds = best.nrounds) 

```

### 先看訓練資料準確度
```{r}
# 先把訓練資料丟回模型做預測
xgb.Prediction <- predict(xgb.Model, dtrain)


#轉換函數 算準確率前再換就好了
theF<-function(A){
  p1 = which(A<300)
  A[p1]=1
  p2 = which(A>=300 & A<1000)
  A[p2]=2
  p3 = which(A>=1000 & A<5000)
  A[p3]=3
  p4 = which(A>=5000)
  A[p4]=4
  return(A)
}
#進行轉換
xgb.Prediction=theF(xgb.Prediction)
train_set.y=theF(as.numeric(train_set.y))


accuracy.xgb <- sum(xgb.Prediction==train_set.y)/length(xgb.Prediction)
accuracy.xgb

table(xgb.Prediction, train_set.y)
```


### 看測試資料準確度
```{r}
# 把測試資料丟進去預測
xgb.Prediction <- predict(xgb.Model, dtest)
xgb.Prediction=theF(xgb.Prediction)
test_set.y=theF(as.numeric(test_set.y))


accuracy.xgb <- sum(xgb.Prediction==test_set.y)/length(xgb.Prediction)
accuracy.xgb


table(xgb.Prediction, test_set.y)

```

## XGBoost準確度也不是很高(可以自己刪減一些沒用的欄位)