# 人工神經網路

## 前處理開始
### 匯入資料或是直接從資料庫拿資料
```{r}
PTT1=read.csv("C:/Users/Student/Desktop/5-模型建立/RawData/PTTContent.csv")
PTT2=read.csv("C:/Users/Student/Desktop/5-模型建立/RawData/PTTComment.csv")
PTT_join = merge(PTT1,PTT2, by='url')
#只留下藥用的欄位
PTT_join2=PTT_join[ ,c(3,4,5,6,7,10,11,12,16)]
rm(PTT1,PTT2,PTT_join)
```

## 類別欄位處理- 深度學習不用攤平 

### 處理time這欄先做分類 分成上午下午晚上半夜 最後貼上數字標籤(最後就不用攤平了)
```{r}
PTT_join2$time= substr(PTT_join2$time ,1,2)
PTT_join2$time = as.character(PTT_join2$time)

b1=which(PTT_join2$time=='07' |PTT_join2$time=='08'|PTT_join2$time=='09'|PTT_join2$time=='10'|PTT_join2$time=='11'|PTT_join2$time=='12' )
PTT_join2[b1,'time']='上午' 
b2=which(PTT_join2$time=='13' |PTT_join2$time=='14'|PTT_join2$time=='15'|PTT_join2$time=='16'|PTT_join2$time=='17'|PTT_join2$time=='18' )
PTT_join2[b2,'time']='下午' 
b3=which(PTT_join2$time=='19' |PTT_join2$time=='20'|PTT_join2$time=='21'|PTT_join2$time=='22'|PTT_join2$time=='23'|PTT_join2$time=='00' )
PTT_join2[b3,'time']='晚上' 
b4=which(PTT_join2$time=='01' |PTT_join2$time=='02'|PTT_join2$time=='03'|PTT_join2$time=='04'|PTT_join2$time=='05'|PTT_join2$time=='06' )
PTT_join2[b4,'time']='半夜' 
rm(b1,b2,b3,b4)

PTT_join2$time = factor(PTT_join2$time,
                        levels = c('上午','下午','晚上','半夜'),
                        labels = c(1,2,3,4))

#確認是不是"factor"
class(PTT_join2$time)
```


###處理area這欄跟上面做一樣的事
```{r}
PTT_join2$area = as.character(PTT_join2$area)
ar0=which(PTT_join2$area==0)
PTT_join2[ar0,'area'] ='其他地區'
ar1=which(PTT_join2$area==1)
PTT_join2[ar1,'area'] ='北區'
ar2=which(PTT_join2$area==2)
PTT_join2[ar2,'area'] ='中區'
ar3=which(PTT_join2$area==3)
PTT_join2[ar3,'area'] ='南區'
ar4=which(PTT_join2$area==4)
PTT_join2[ar4,'area'] ='東區'
rm(ar0,ar1,ar2,ar3,ar4)

PTT_join2$area = factor(PTT_join2$area,
                        levels = c('其他地區','北區','中區','南區','東區'),
                        labels = c(0,1,2,3,4))

#確認是不是"factor"
class(PTT_join2$area)
```




### 增加欄位-文章關鍵字出現次數
```{r}
PTT3 = PTT_join2
library(stringr)
PTT3$chocolate <- as.integer(str_count(PTT3$content,"巧克力"))
PTT3$cookie <- as.integer(str_count(PTT3$content,"餅乾"))
PTT3$butter <- as.integer(str_count(PTT3$content,"奶油"))
PTT3$strawberry <- as.integer(str_count(PTT3$content,"草莓"))
PTT3$cheese <- as.integer(str_count(PTT3$content,"乳酪"))
PTT3$milk <- as.integer(str_count(PTT3$content,"牛奶"))
PTT3$egg <- as.integer(str_count(PTT3$content,"蛋"))
PTT3$coffee <- as.integer(str_count(PTT3$content,"咖啡"))
PTT3$lemon <- as.integer(str_count(PTT3$content,"檸檬"))
PTT3$beef <- as.integer(str_count(PTT3$content,"牛肉"))
```

### 增加內文字元數
```{r include=FALSE}
library(jiebaR)
PTT3$content = as.character(PTT3$content) 
PTT3$comment = as.character(PTT3$comment) 
PTT3$nchar1 =nchar(PTT3$content)  #原文字元數
PTT3$nchar2 =nchar(PTT3$comment)  #回文字元數

#無人回應y1就是1 (注意不要執行2次)
PTT3$y1 <- ifelse(PTT3$nchar2==0, 1, 0) 
```


### 留下要用到的欄位 
```{r}
PTT4 = PTT3[ ,c(1,2,3,4,5,6,10,11,12,13,14,15,16,17,18,19,20,22)]

PTT4$y1 = as.integer(PTT4$y1)
```


### 分訓練、測試資料
```{r}
library(caTools)
set.seed(11)
split =sample.split(PTT4$y1 , SplitRatio =0.8)
trainingset = subset(PTT4, subset =(split==TRUE) )
testset = subset(PTT4, subset =(split==FALSE) )
rm(split)
```

### 數值型欄位要正規化就好
```{r}
trainingset[ ,7:17]= scale(trainingset[ ,7:17])
testset[ ,7:17]= scale(testset[ ,7:17])
```
##深度學習的資料前處理結束



## 建立ANN模型
```{r}
#要有JAVA環境才能裝
library(h2o) 
#nthreads =-1表示使用電腦所有的核都下去跑
h2o.init(nthreads = -1) 

classifier2 = h2o.deeplearning(y = 'y1',
                              training_frame = as.h2o(trainingset),
                              activation = 'Rectifier', 
                              hidden = c(9,6,4),
                              epochs = 300,  
                              train_samples_per_iteration = -2)

```

##　看準確度 測試資料
```{r}
prob_pred = h2o.predict(classifier2, 
                        newdata = as.h2o(testset[-18]))#除了第18欄 其他都是X

y_pred = (prob_pred > 0.6)
y_pred = as.vector(y_pred)

```


### 混淆矩陣
```{r}
cm = table(testset[,18], y_pred)
cm
```


## 看準確度
```{r}
accuracy_rate <- sum(testset[,18]==y_pred)/length(y_pred)
accuracy_rate
```